term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: 1e1e2e
term_foreground: cdd6f4
term_background_bright: 585b70

timeout: 0
interface_resolution: 1600x900
interface_branding:
theme_background: 0x1e1e2e
theme_foreground: 0xcdd6f4
theme_margin: 64
theme_margin_gradient: 16

/Dunit OS - Terminal Test
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    cmdline: mode=terminal
    kaslr: no
