term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: 801e1e2e
term_foreground: cdd6f4
term_background_bright: 585b70
term_backdrop: boot():/boot/limine.png
wallpaper: boot():/boot/limine.png

timeout: 10
interface_resolution: 1600x900
interface_branding: ""

theme_background: 0x801e1e2e
theme_foreground: 0xcdd6f4
theme_margin: 150
theme_margin_gradient: 48

/  »  DUNIT OS // TERMINAL MODE
    comment: System-level access and kernel diagnostics.
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/installer-esp.img
    cmdline: mode=terminal
    kaslr: no

/  »  DUNIT OS // GRAPHICAL INTERFACE
    comment: Experimental window manager and desktop shell.
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/installer-esp.img
    resolution: 1600x900x32
    kaslr: no
