timeout: 5
interface_resolution: 1024x768
interface_branding: Dunit OS (Green Tea) Boot Menu
theme_background: 0x002b36
theme_foreground: 0x93a1a1
theme_margin: 64
theme_margin_gradient: 8

/Dunit OS - GUI Mode (with Desktop Environment)
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    resolution: 1024x768x32
    kaslr: no

/Dunit OS - Terminal Mode (Text Only)
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    cmdline: mode=terminal
    kaslr: no
    textmode: yes
