#!/bin/bash

echo "Uploading Dunit OS source code to server..."
echo ""
echo "Archive location: /tmp/dunit-os-source.tar.gz"
echo "Archive size: 1.5M"
echo ""
echo "To upload manually, run:"
echo "scp /tmp/dunit-os-source.tar.gz root@2.27.40.246:/root/"
echo ""
echo "Password: vH3mQ2aM4vaDhh"
echo ""
echo "After upload, on the server run:"
echo "cd /root"
echo "tar -xzf dunit-os-source.tar.gz"
echo "cd dunit-os"
echo "make"
