// GENERATED by tools/gen_abi.py from abi/errno.abi — do not edit by hand.
// Dunit Userspace ABI v0: error numbers. Syscalls return the negated value
// in rax; magnitudes equal POSIX errno (identity mapping).

pub const EPERM: isize = -1;
pub const ENOENT: isize = -2;
pub const EINTR: isize = -4;
pub const EIO: isize = -5;
pub const EBADF: isize = -9;
pub const ECHILD: isize = -10;
pub const EAGAIN: isize = -11;
pub const ENOMEM: isize = -12;
pub const EACCES: isize = -13;
pub const EFAULT: isize = -14;
pub const EBUSY: isize = -16;
pub const EEXIST: isize = -17;
pub const ENOTDIR: isize = -20;
pub const EISDIR: isize = -21;
pub const EINVAL: isize = -22;
pub const ENFILE: isize = -23;
pub const EPIPE: isize = -32;
pub const ENAMETOOLONG: isize = -36;
pub const ENOSYS: isize = -38;
pub const ENOTEMPTY: isize = -39;
pub const EMSGSIZE: isize = -90;
pub const EOPNOTSUPP: isize = -95;
pub const ENOBUFS: isize = -105;

/// Short name for a negative Dunit error code (`"ERR"` if unknown).
pub fn error_name(code: isize) -> &'static str {
    match code {
        -1 => "EPERM",
        -2 => "ENOENT",
        -4 => "EINTR",
        -5 => "EIO",
        -9 => "EBADF",
        -10 => "ECHILD",
        -11 => "EAGAIN",
        -12 => "ENOMEM",
        -13 => "EACCES",
        -14 => "EFAULT",
        -16 => "EBUSY",
        -17 => "EEXIST",
        -20 => "ENOTDIR",
        -21 => "EISDIR",
        -22 => "EINVAL",
        -23 => "ENFILE",
        -32 => "EPIPE",
        -36 => "ENAMETOOLONG",
        -38 => "ENOSYS",
        -39 => "ENOTEMPTY",
        -90 => "EMSGSIZE",
        -95 => "EOPNOTSUPP",
        -105 => "ENOBUFS",
        _ => "ERR",
    }
}
