// GENERATED by tools/gen_abi.py from abi/rights.abi — do not edit by hand.
// Dunit Userspace ABI v0: handle capability bits. Rights only narrow on
// transfer, never widen.

pub const RIGHT_READ: u32 = 1 << 0;
pub const RIGHT_WRITE: u32 = 1 << 1;
pub const RIGHT_MAP: u32 = 1 << 2;
pub const RIGHT_SIGNAL: u32 = 1 << 3;
pub const RIGHT_TRANSFER: u32 = 1 << 4;
pub const RIGHT_DISPLAY_MASTER: u32 = 1 << 5;
pub const RIGHT_INPUT_MASTER: u32 = 1 << 6;
