/* GENERATED by tools/gen_abi.py from abi/errno.abi - do not edit by hand. */
/* Dunit Userspace ABI v0: error numbers (positive; == POSIX errno). A syscall
   reports failure by returning -VALUE in rax. Prefixed to avoid clashing with
   the musl fork's own <errno.h>; the adapter maps these 1:1 to POSIX errno. */
#ifndef DUNIT_ERRNO_H
#define DUNIT_ERRNO_H

#define DUNIT_EPERM 1
#define DUNIT_ENOENT 2
#define DUNIT_EINTR 4
#define DUNIT_EIO 5
#define DUNIT_EBADF 9
#define DUNIT_ECHILD 10
#define DUNIT_EAGAIN 11
#define DUNIT_ENOMEM 12
#define DUNIT_EACCES 13
#define DUNIT_EFAULT 14
#define DUNIT_EBUSY 16
#define DUNIT_EEXIST 17
#define DUNIT_ENOTDIR 20
#define DUNIT_EISDIR 21
#define DUNIT_EINVAL 22
#define DUNIT_ENFILE 23
#define DUNIT_EPIPE 32
#define DUNIT_ENAMETOOLONG 36
#define DUNIT_ENOSYS 38
#define DUNIT_ENOTEMPTY 39
#define DUNIT_EMSGSIZE 90
#define DUNIT_EOPNOTSUPP 95
#define DUNIT_ENOBUFS 105

#endif /* DUNIT_ERRNO_H */
