/* GENERATED by tools/gen_abi.py from abi/rights.abi - do not edit by hand. */
/* Dunit Userspace ABI v0: handle capability bits (rights only narrow). */
#ifndef DUNIT_RIGHTS_H
#define DUNIT_RIGHTS_H

#define DUNIT_RIGHT_READ (1u << 0)
#define DUNIT_RIGHT_WRITE (1u << 1)
#define DUNIT_RIGHT_MAP (1u << 2)
#define DUNIT_RIGHT_SIGNAL (1u << 3)
#define DUNIT_RIGHT_TRANSFER (1u << 4)
#define DUNIT_RIGHT_DISPLAY_MASTER (1u << 5)
#define DUNIT_RIGHT_INPUT_MASTER (1u << 6)

#endif /* DUNIT_RIGHTS_H */
