#!/usr/bin/env python3
"""Generate kernel/src/console_font.rs from a PSF2 8x16 console font.

The kernel's framebuffer terminal (kernel/src/terminal.rs) renders with a
built-in 8x16 bitmap font so the console looks like a real Linux TTY. This tool
converts a PSF2 8x16 font (e.g. the Linux default console font
/usr/share/kbd/consolefonts/default8x16.psfu.gz) into a committed Rust data
module, so the kernel has no build- or run-time dependency on the host.

The emitted data is a 256-glyph table of 16 rows x 8 bits each — a plain bitmap,
which is uncopyrightable typeface data. Re-run to swap the console font.

Usage:
    python3 tools/gen_console_font.py \
        /usr/share/kbd/consolefonts/default8x16.psfu.gz \
        kernel/src/console_font.rs
"""

from __future__ import annotations

import gzip
import struct
import sys
from pathlib import Path

PSF2_MAGIC = bytes([0x72, 0xB5, 0x4A, 0x86])


def load_psf2_8x16(path: Path) -> list[list[int]]:
    raw = path.read_bytes()
    if path.suffix == ".gz" or raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    if raw[:4] != PSF2_MAGIC:
        raise SystemExit(f"not a PSF2 font: {path}")
    _ver, hdr, _flags, length, charsize, height, width = struct.unpack(
        "<IIIIIII", raw[4:32]
    )
    if (width, height, charsize) != (8, 16, 16):
        raise SystemExit(f"expected 8x16 (16 bytes/glyph), got {width}x{height}/{charsize}")
    glyphs = []
    for i in range(min(length, 256)):
        start = hdr + i * charsize
        glyphs.append(list(raw[start:start + charsize]))
    while len(glyphs) < 256:
        glyphs.append([0] * 16)
    return glyphs


def emit(glyphs: list[list[int]], src: Path, out: Path) -> None:
    lines = [
        "// GENERATED by tools/gen_console_font.py — do not edit by hand.",
        f"// Source: {src} (PSF2, 8x16). Re-run the tool to regenerate.",
        "//",
        "// Classic 8x16 VGA/console bitmap: 256 glyphs, 16 rows, bit 7 = leftmost",
        "// pixel. This is the kernel framebuffer terminal's built-in font, giving",
        "// the console a real Linux-TTY look (kernel/src/terminal.rs).",
        "",
        "pub static FONT_8X16: [[u8; 16]; 256] = [",
    ]
    for g in glyphs:
        body = ", ".join(f"0x{b:02x}" for b in g)
        lines.append(f"    [{body}],")
    lines.append("];")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[FONT] wrote {out} (256 glyphs x 16 rows)")


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    emit(load_psf2_8x16(Path(sys.argv[1])), Path(sys.argv[1]), Path(sys.argv[2]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
