#!/usr/bin/env python3
"""Generate the Dunit Userspace ABI v0 syscall definitions from one manifest.

`abi/syscalls.abi` is the single source of truth for syscall numbers. This tool
regenerates the language-specific consumers from it and verifies the kernel
agrees, so the number space can never silently drift across kernel, libdunit and
the C sysroot (the latter is what the Dunit musl fork will consume).

Outputs (committed, never hand-edited):
  - userspace/libdunit/src/syscall_numbers.rs   Rust: `pub const SYSCALL_<NAME>`
  - abi/include/dunit/syscall.h                 C:    `#define SYS_<NAME>`

Check: the kernel's `enum Syscall` (kernel/src/syscall/mod.rs) must map exactly
the same {number -> CanonicalName}; any mismatch is a hard error (exit 2).

Usage: python3 tools/gen_abi.py        # regenerate + check
       python3 tools/gen_abi.py --check # verify only, write nothing (for CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "abi/syscalls.abi"
RUST_OUT = ROOT / "userspace/libdunit/src/syscall_numbers.rs"
C_OUT = ROOT / "abi/include/dunit/syscall.h"
KERNEL = ROOT / "kernel/src/syscall/mod.rs"
ERRNO_MANIFEST = ROOT / "abi/errno.abi"
ERRNO_RUST_OUT = ROOT / "userspace/libdunit/src/errno_numbers.rs"
ERRNO_C_OUT = ROOT / "abi/include/dunit/errno.h"
RIGHTS_MANIFEST = ROOT / "abi/rights.abi"
RIGHTS_RUST_OUT = ROOT / "userspace/libdunit/src/rights_numbers.rs"
RIGHTS_C_OUT = ROOT / "abi/include/dunit/rights.h"
KERNEL_HANDLE = ROOT / "kernel/src/handle.rs"


def screaming(camel: str) -> str:
    """CamelCase -> SCREAMING_SNAKE (GetCwd -> GET_CWD, Fsck -> FSCK)."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", camel).upper()


def load_manifest() -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        num, name = line.split()
        out.append((int(num), name))
    out.sort()
    nums = [n for n, _ in out]
    if nums != list(range(len(nums))):
        raise SystemExit(f"manifest numbers must be contiguous from 0: {nums}")
    return out


def load_kernel() -> dict[int, str]:
    text = KERNEL.read_text(encoding="utf-8")
    body = re.search(r"enum Syscall\s*\{(.*?)\n\}", text, re.S)
    if not body:
        raise SystemExit("could not find `enum Syscall` in the kernel")
    pairs = re.findall(r"^\s*([A-Z][A-Za-z0-9]+)\s*=\s*(\d+)\s*,", body.group(1), re.M)
    return {int(n): name for name, n in pairs}
# __GEN_ABI_APPEND__

def check_kernel(manifest: list[tuple[int, str]]) -> None:
    kernel = load_kernel()
    want = {n: name for n, name in manifest}
    if kernel != want:
        lines = ["kernel `enum Syscall` disagrees with abi/syscalls.abi:"]
        for n in sorted(set(want) | set(kernel)):
            if want.get(n) != kernel.get(n):
                lines.append(f"  {n}: manifest={want.get(n)!r} kernel={kernel.get(n)!r}")
        print("\n".join(lines), file=sys.stderr)
        raise SystemExit(2)


def render_rust(manifest: list[tuple[int, str]]) -> str:
    out = [
        "// GENERATED by tools/gen_abi.py from abi/syscalls.abi — do not edit by hand.",
        "// Dunit Userspace ABI v0: syscall numbers, the single source of truth for",
        "// libdunit. Edit abi/syscalls.abi and re-run the tool to change the ABI.",
        "",
    ]
    for n, name in manifest:
        out.append(f"pub const SYSCALL_{screaming(name)}: usize = {n};")
    return "\n".join(out) + "\n"


def render_c(manifest: list[tuple[int, str]]) -> str:
    out = [
        "/* GENERATED by tools/gen_abi.py from abi/syscalls.abi - do not edit by hand. */",
        "/* Dunit Userspace ABI v0: syscall numbers for the C sysroot (musl fork). */",
        "#ifndef DUNIT_SYSCALL_H",
        "#define DUNIT_SYSCALL_H",
        "",
    ]
    for n, name in manifest:
        out.append(f"#define SYS_{screaming(name)} {n}")
    out += ["", f"#define DUNIT_SYSCALL_COUNT {len(manifest)}", "", "#endif /* DUNIT_SYSCALL_H */"]
    return "\n".join(out) + "\n"


def load_errno() -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for line in ERRNO_MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            num, name = line.split()
            out.append((int(num), name))
    out.sort()
    return out


def check_kernel_errno(manifest: list[tuple[int, str]]) -> None:
    text = KERNEL.read_text(encoding="utf-8")
    kernel = {name: -int(v) for name, v in
              re.findall(r"(?:pub )?const (E[A-Z]+): i64 = (-\d+);", text)}
    want = {name: n for n, name in manifest}
    if kernel != want:
        lines = ["kernel errno consts disagree with abi/errno.abi:"]
        for name in sorted(set(want) | set(kernel)):
            if want.get(name) != kernel.get(name):
                lines.append(f"  {name}: manifest={want.get(name)!r} kernel={kernel.get(name)!r}")
        print("\n".join(lines), file=sys.stderr)
        raise SystemExit(2)


def render_errno_rust(manifest: list[tuple[int, str]]) -> str:
    out = [
        "// GENERATED by tools/gen_abi.py from abi/errno.abi — do not edit by hand.",
        "// Dunit Userspace ABI v0: error numbers. Syscalls return the negated value",
        "// in rax; magnitudes equal POSIX errno (identity mapping).",
        "",
    ]
    for n, name in manifest:
        out.append(f"pub const {name}: isize = -{n};")
    out += ["", "/// Short name for a negative Dunit error code (`\"ERR\"` if unknown).",
            "pub fn error_name(code: isize) -> &'static str {", "    match code {"]
    for n, name in manifest:
        out.append(f"        -{n} => \"{name}\",")
    out += ["        _ => \"ERR\",", "    }", "}"]
    return "\n".join(out) + "\n"


def render_errno_c(manifest: list[tuple[int, str]]) -> str:
    out = [
        "/* GENERATED by tools/gen_abi.py from abi/errno.abi - do not edit by hand. */",
        "/* Dunit Userspace ABI v0: error numbers (positive; == POSIX errno). A syscall",
        "   reports failure by returning -VALUE in rax. Prefixed to avoid clashing with",
        "   the musl fork's own <errno.h>; the adapter maps these 1:1 to POSIX errno. */",
        "#ifndef DUNIT_ERRNO_H",
        "#define DUNIT_ERRNO_H",
        "",
    ]
    for n, name in manifest:
        out.append(f"#define DUNIT_{name} {n}")
    out += ["", "#endif /* DUNIT_ERRNO_H */"]
    return "\n".join(out) + "\n"


def load_rights() -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for line in RIGHTS_MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            bit, name = line.split()
            out.append((int(bit), name))
    out.sort()
    return out


def check_kernel_rights(manifest: list[tuple[int, str]]) -> None:
    text = KERNEL_HANDLE.read_text(encoding="utf-8")
    kernel = {name: int(bit) for name, bit in
              re.findall(r"pub const RIGHT_([A-Z_]+): u32 = 1 << (\d+);", text)}
    want = {name: bit for bit, name in manifest}
    if kernel != want:
        lines = ["kernel handle rights disagree with abi/rights.abi:"]
        for name in sorted(set(want) | set(kernel)):
            if want.get(name) != kernel.get(name):
                lines.append(f"  RIGHT_{name}: manifest={want.get(name)!r} kernel={kernel.get(name)!r}")
        print("\n".join(lines), file=sys.stderr)
        raise SystemExit(2)


def render_rights_rust(manifest: list[tuple[int, str]]) -> str:
    out = [
        "// GENERATED by tools/gen_abi.py from abi/rights.abi — do not edit by hand.",
        "// Dunit Userspace ABI v0: handle capability bits. Rights only narrow on",
        "// transfer, never widen.",
        "",
    ]
    for bit, name in manifest:
        out.append(f"pub const RIGHT_{name}: u32 = 1 << {bit};")
    return "\n".join(out) + "\n"


def render_rights_c(manifest: list[tuple[int, str]]) -> str:
    out = [
        "/* GENERATED by tools/gen_abi.py from abi/rights.abi - do not edit by hand. */",
        "/* Dunit Userspace ABI v0: handle capability bits (rights only narrow). */",
        "#ifndef DUNIT_RIGHTS_H",
        "#define DUNIT_RIGHTS_H",
        "",
    ]
    for bit, name in manifest:
        out.append(f"#define DUNIT_RIGHT_{name} (1u << {bit})")
    out += ["", "#endif /* DUNIT_RIGHTS_H */"]
    return "\n".join(out) + "\n"


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    manifest = load_manifest()
    check_kernel(manifest)
    errno = load_errno()
    check_kernel_errno(errno)
    rights = load_rights()
    check_kernel_rights(rights)
    rust, c = render_rust(manifest), render_c(manifest)
    errno_rust, errno_c = render_errno_rust(errno), render_errno_c(errno)
    rights_rust, rights_c = render_rights_rust(rights), render_rights_c(rights)
    outputs = [(RUST_OUT, rust), (C_OUT, c), (ERRNO_RUST_OUT, errno_rust), (ERRNO_C_OUT, errno_c),
               (RIGHTS_RUST_OUT, rights_rust), (RIGHTS_C_OUT, rights_c)]
    if check_only:
        stale = [p for p, text in outputs if p.read_text(encoding="utf-8") != text]
        if stale:
            print("stale generated ABI files; run tools/gen_abi.py: "
                  + ", ".join(str(p.relative_to(ROOT)) for p in stale), file=sys.stderr)
            return 2
        print(f"ABI v0 OK: {len(manifest)} syscalls + {len(errno)} errno + {len(rights)} rights, "
              "kernel + outputs in sync")
        return 0
    for p, text in outputs:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    print(f"[ABI] {len(manifest)} syscalls + {len(errno)} errno + {len(rights)} rights "
          "-> libdunit + abi/include (kernel verified)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
