#!/usr/bin/env python3
"""Generate the Dunit Userspace ABI v0 syscall definitions from one manifest.

`abi/syscalls.abi` is the single source of truth for syscall numbers. This tool
regenerates the language-specific consumers from it and verifies the kernel
agrees, so the number space can never silently drift across kernel, libdunit and
the C sysroot (the latter is what the Dunit musl fork will consume).

Outputs (committed, never hand-edited):
  - userspace/libdunit/src/syscall_numbers.rs   Rust: `pub const SYSCALL_<NAME>`
  - abi/include/dunit/syscall.h                 C:    `#define SYS_<NAME>`

Check: the kernel's `enum Syscall` (kernel/src/syscall/mod.rs) must map exactly
the same {number -> CanonicalName}; any mismatch is a hard error (exit 2).

Usage: python3 tools/gen_abi.py        # regenerate + check
       python3 tools/gen_abi.py --check # verify only, write nothing (for CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "abi/syscalls.abi"
RUST_OUT = ROOT / "userspace/libdunit/src/syscall_numbers.rs"
C_OUT = ROOT / "abi/include/dunit/syscall.h"
KERNEL = ROOT / "kernel/src/syscall/mod.rs"


def screaming(camel: str) -> str:
    """CamelCase -> SCREAMING_SNAKE (GetCwd -> GET_CWD, Fsck -> FSCK)."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", camel).upper()


def load_manifest() -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for line in MANIFEST.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        num, name = line.split()
        out.append((int(num), name))
    out.sort()
    nums = [n for n, _ in out]
    if nums != list(range(len(nums))):
        raise SystemExit(f"manifest numbers must be contiguous from 0: {nums}")
    return out


def load_kernel() -> dict[int, str]:
    text = KERNEL.read_text(encoding="utf-8")
    body = re.search(r"enum Syscall\s*\{(.*?)\n\}", text, re.S)
    if not body:
        raise SystemExit("could not find `enum Syscall` in the kernel")
    pairs = re.findall(r"^\s*([A-Z][A-Za-z0-9]+)\s*=\s*(\d+)\s*,", body.group(1), re.M)
    return {int(n): name for name, n in pairs}
# __GEN_ABI_APPEND__

def check_kernel(manifest: list[tuple[int, str]]) -> None:
    kernel = load_kernel()
    want = {n: name for n, name in manifest}
    if kernel != want:
        lines = ["kernel `enum Syscall` disagrees with abi/syscalls.abi:"]
        for n in sorted(set(want) | set(kernel)):
            if want.get(n) != kernel.get(n):
                lines.append(f"  {n}: manifest={want.get(n)!r} kernel={kernel.get(n)!r}")
        print("\n".join(lines), file=sys.stderr)
        raise SystemExit(2)


def render_rust(manifest: list[tuple[int, str]]) -> str:
    out = [
        "// GENERATED by tools/gen_abi.py from abi/syscalls.abi — do not edit by hand.",
        "// Dunit Userspace ABI v0: syscall numbers, the single source of truth for",
        "// libdunit. Edit abi/syscalls.abi and re-run the tool to change the ABI.",
        "",
    ]
    for n, name in manifest:
        out.append(f"pub const SYSCALL_{screaming(name)}: usize = {n};")
    return "\n".join(out) + "\n"


def render_c(manifest: list[tuple[int, str]]) -> str:
    out = [
        "/* GENERATED by tools/gen_abi.py from abi/syscalls.abi - do not edit by hand. */",
        "/* Dunit Userspace ABI v0: syscall numbers for the C sysroot (musl fork). */",
        "#ifndef DUNIT_SYSCALL_H",
        "#define DUNIT_SYSCALL_H",
        "",
    ]
    for n, name in manifest:
        out.append(f"#define SYS_{screaming(name)} {n}")
    out += ["", f"#define DUNIT_SYSCALL_COUNT {len(manifest)}", "", "#endif /* DUNIT_SYSCALL_H */"]
    return "\n".join(out) + "\n"


def main() -> int:
    check_only = "--check" in sys.argv[1:]
    manifest = load_manifest()
    check_kernel(manifest)
    rust, c = render_rust(manifest), render_c(manifest)
    if check_only:
        ok = RUST_OUT.read_text(encoding="utf-8") == rust and C_OUT.read_text(encoding="utf-8") == c
        if not ok:
            print("generated ABI files are stale; run tools/gen_abi.py", file=sys.stderr)
            return 2
        print(f"ABI v0 OK: {len(manifest)} syscalls, kernel + outputs in sync")
        return 0
    C_OUT.parent.mkdir(parents=True, exist_ok=True)
    RUST_OUT.write_text(rust, encoding="utf-8")
    C_OUT.write_text(c, encoding="utf-8")
    print(f"[ABI] {len(manifest)} syscalls -> {RUST_OUT.relative_to(ROOT)} + {C_OUT.relative_to(ROOT)} (kernel verified)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
